export const SET_PAGINATION_LINKS = 'SET_PAGINATION_LINKS'
export const SET_RECENT_SNIPPETS = 'SET_RECENT_SNIPPETS'
export const SET_SNIPPET = 'SET_SNIPPET'
export const SET_SYNTAXES = 'SET_SYNTAXES'
