let syntaxes = [
  'text',
  'c_cpp',
  'csharp',
  'golang',
  'java',
  'javascript',
  'php',
  'perl',
  'python',
  'ruby',
  'rust',
  'css',
  'html',
  'objectivec',
  'swift',
  'clojure',
  'lisp',
  'haskell',
  'scala',
  'scheme',
  'actionscript',
  'ada',
  'apache_conf',
  'asciidoc',
  'assembly_x86',
  'batchfile',
  'cobol',
  'coffee',
  'd',
  'dart',
  'diff',
  'dockerfile',
  'dot',
  'ejs',
  'elixir',
  'elm',
  'erlang',
  'fortran',
  'gitignore',
  'glsl',
  'gobstones',
  'graphqlschema',
  'groovy',
  'haml',
  'handlebars',
  'haxe',
  'hjson',
  'ini',
  'jade',
  'json',
  'jsp',
  'jsx',
  'julia',
  'kotlin',
  'latex',
  'less',
  'livescript',
  'lua',
  'makefile',
  'markdown',
  'matlab',
  'mel',
  'mysql',
  'nix',
  'nsis',
  'ocaml',
  'pascal',
  'pgsql',
  'powershell',
  'prolog',
  'protobuf',
  'r',
  'rdoc',
  'rst',
  'sass',
  'scad',
  'scss',
  'sh',
  'sjs',
  'smarty',
  'sql',
  'stylus',
  'svg',
  'tcl',
  'tex',
  'textile',
  'toml',
  'tsx',
  'twig',
  'typescript',
  'vala',
  'vbscript',
  'verilog',
  'vhdl',
  'xml',
  'yaml',
  'django',
]

let snippet = {
  title: 'Test snippet',
  syntax: 'text',
  tags: ['test', 'tags'],
  created_at: '2019-10-07T07:21:36',
  updated_at: '2019-10-07T07:21:36',
  id: 1997,
  content: 'This is a test snippet',
}

let recentSnippets = [
  {
    title: 'Test snippet',
    syntax: 'text',
    tags: ['test', 'tag'],
    created_at: '2019-10-07T09:19:43',
    updated_at: '2019-10-07T09:19:43',
    id: 364092,
    content: 'Nigil',
  },
  {
    title: 'Test snippet',
    syntax: 'text',
    tags: ['test', 'tags'],
    created_at: '2019-10-07T09:08:40',
    updated_at: '2019-10-07T09:08:40',
    id: 364091,
    content: 'This is a test snippet',
  },
  {
    title: 'Test snippet',
    syntax: 'text',
    tags: ['test', 'tags'],
    created_at: '2019-10-07T07:21:36',
    updated_at: '2019-10-07T07:21:36',
    id: 364090,
    content: 'This is a test snippet',
  },
  {
    title: 'Kumar',
    syntax: 'text',
    tags: ['Test'],
    created_at: '2019-10-07T07:03:35',
    updated_at: '2019-10-07T07:03:35',
    id: 364089,
    content: 'Nikhil',
  },
  {
    title: 'themeProvider',
    syntax: 'javascript',
    tags: ['react', 'hook', 'theme', 'provider'],
    created_at: '2019-10-06T19:12:11',
    updated_at: '2019-10-06T19:12:11',
    id: 364088,
    content:
      "import React from 'react'\n\nconst themes = {\n  dark: {\n    bgColor: '#000',\n    color: '#fff'\n  },\n  light: {\n    bgColor: '#fff',\n    color: '#000'\n  }\n}\n\nconst initialState = {\n  dark: false,\n  theme: themes.light,\n  toggleMode: () => {}\n}\n\nconst ThemeContext = React.createContext(initialState)\n\nfunction ThemeProvider({ children }) {\n  const [dark, setDark] = React.useState(false)\n\n  React.useEffect(() => {\n    const isDark = localStorage.getItem('dark') === 'true'\n    setDark(isDark)\n  }, [dark])\n\n  const toggleMode = () => {\n    const isDark = !dark\n    localStorage.setItem('dark', JSON.stringify(isDark))\n    setDark(isDark)\n  }\n\n  const theme = dark ? themes.dark : themes.light\n\n  return (\n    <ThemeContext.Provider value={{ theme, dark, toggleMode }}>\n      {children}\n    </ThemeContext.Provider>\n  )\n}\n\nexport { ThemeProvider, ThemeContext }\n",
  },
  {
    title: 'flask',
    syntax: 'python',
    tags: ['flask', 'doc'],
    created_at: '2019-10-06T16:03:25',
    updated_at: '2019-10-06T16:03:25',
    id: 364087,
    content:
      "from flask import Flask, escape, url_for\n\napp = Flask(__name__)\n\n@app.route('/')\ndef index():\n    return 'index'\n\n@app.route('/login')\ndef login():\n    return 'login'\n\n@app.route('/user/<username>')\ndef profile(username):\n    return '{}\\'s profile'.format(escape(username))\n\nwith app.test_request_context():\n    print(url_for('index'))\n    print(url_for('login'))\n    print(url_for('login', next='/'))\n    print(url_for('profile', username='John Doe'))",
  },
  {
    title: '',
    syntax: 'java',
    tags: [],
    created_at: '2019-10-05T09:07:22',
    updated_at: '2019-10-05T09:07:22',
    id: 364086,
    content: 'asdsdsad',
  },
  {
    title: 'dsfsdf',
    syntax: 'text',
    tags: ['dsfsdf'],
    created_at: '2019-10-05T08:24:07',
    updated_at: '2019-10-05T08:24:07',
    id: 364085,
    content: 'scsd',
  },
  {
    title: 'jhguyg',
    syntax: 'text',
    tags: ['yfgyuhgv'],
    created_at: '2019-10-05T08:16:43',
    updated_at: '2019-10-05T08:16:43',
    id: 364084,
    content: 'ghjgjh',
  },
  {
    title: '',
    syntax: 'javascript',
    tags: [],
    created_at: '2019-10-05T08:15:04',
    updated_at: '2019-10-05T08:15:04',
    id: 364083,
    content: "console.log('hello')",
  },
  {
    title: '',
    syntax: 'text',
    tags: [],
    created_at: '2019-10-05T05:19:02',
    updated_at: '2019-10-05T05:19:02',
    id: 364082,
    content: 'vsadnvjsav',
  },
  {
    title: '',
    syntax: 'text',
    tags: [],
    created_at: '2019-10-05T05:18:58',
    updated_at: '2019-10-05T05:18:58',
    id: 364081,
    content: 'dncaksdvasv',
  },
  {
    title: '',
    syntax: 'text',
    tags: [],
    created_at: '2019-10-05T05:18:55',
    updated_at: '2019-10-05T05:18:55',
    id: 364080,
    content: 'dscknasdlcadsvadsc',
  },
  {
    title: '',
    syntax: 'text',
    tags: [],
    created_at: '2019-10-05T05:18:51',
    updated_at: '2019-10-05T05:18:51',
    id: 364079,
    content: 'xcjasjdkcd',
  },
  {
    title: '',
    syntax: 'text',
    tags: [],
    created_at: '2019-10-05T05:17:51',
    updated_at: '2019-10-05T05:17:51',
    id: 364078,
    content: 'acadcdaca',
  },
  {
    title: '',
    syntax: 'python',
    tags: [],
    created_at: '2019-10-05T05:17:20',
    updated_at: '2019-10-05T05:17:20',
    id: 364077,
    content: 'dc dsc',
  },
  {
    title: 'tetst',
    syntax: 'text',
    tags: ['f'],
    created_at: '2019-10-02T19:26:59',
    updated_at: '2019-10-02T19:26:59',
    id: 364076,
    content:
      'The Flask mega tutorial by Miguel Grinberg is a perfect starting resource for using this web framework. Each post focuses on a single topic and builds on previous posts. The series includes 18 parts: #1 Hello World, #2 Templates, #3 Web Forms, #4 Database, #5 User Logins, #6 Profile Page and Avatars, #7 Unit Testing, #8 Followers, Contacts, and Friends, #9 Pagination, #10 Full Text Search, #11 Email Support, #12 Facelift, #13 Dates and Times, #14 I18n and L10n, #15 Ajax, #16 Debugging, Testing and Profiling, #17 Deployment on Linux and #18 Deployment on the Heroku Cloud. Miguel also wrote and recorded numerous Flask Web Development content including a great book and video book that are excellent resources worth the price, especially to support his continuous revisions to the content.',
  },
  {
    title: '',
    syntax: 'text',
    tags: [],
    created_at: '2019-10-01T08:43:48',
    updated_at: '2019-10-01T08:43:48',
    id: 364075,
    content:
      "var hero = {\n    _name: 'John Doe',\n    getSecretIdentity: function (){\n        return this._name;\n    }\n};\n\nvar stoleSecretIdentity = hero.getSecretIdentity;\n\nconsole.log(stoleSecretIdentity()); // ?\nconsole.log(hero.getSecretIdentity()); // ?",
  },
  {
    title: '',
    syntax: 'text',
    tags: [],
    created_at: '2019-10-01T08:40:09',
    updated_at: '2019-10-01T08:40:09',
    id: 364074,
    content: "setTimeout(function() { console.log('hi'); }, 0);\nfor(;;){}",
  },
  {
    title: '',
    syntax: 'text',
    tags: [],
    created_at: '2019-10-01T08:38:58',
    updated_at: '2019-10-01T08:38:58',
    id: 364073,
    content:
      'setTimeout(function() { console.log(i); }, i * 1000 );\nfor(;;){}',
  },
]

let titles = recentSnippets.map(
  snippet => snippet.title || `#${snippet.id}, Untitled`
)

module.exports = {
  syntaxes,
  snippet,
  recentSnippets,
  titles,
}
