name: Release

on:
  push:
    tags:
      - 'v[1-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: |
        npm install
        npm run build
        tar cvzf dist.tar.gz -C dist/ .
    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_TAG_NAME: ${GITHUB_REF#refs/*/}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist.tar.gz
        asset_name: xsnippet-web-${GIT_TAG_NAME}.tar.gz
        asset_content_type: application/gzip
